# application.properties
server.port=8080
server.address=0.0.0.0

# Datasource properties
spring.datasource.url=jdbc:postgresql://dpg-cqp0tdogph6c73femsog-a.oregon-postgres.render.com:5432/skt_shop_db
spring.datasource.username=skt_shop_db_user
spring.datasource.password=T6hGe7KXZ3R4iMRlw0p7wYnqpPrJ4YtX
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Mail properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${THESHAPE_USERNAME}
spring.mail.password=${THESHAPE_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
